AWSTemplateFormatVersion: 2010-09-09

Description: |
  Test template for AWS CloudFormation
  
Resources:
  mysecuritygroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH and HTTP access
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort:  22
          ToPort:  22
          CidrIp:  0.0.0.0/0
        - IpProtocol: tcp
          FromPort:  80
          ToPort:  80
          CidrIp:  0.0.0.0/0

  MyInstance:
      Type: AWS::EC2::Instance
      Properties:
        ImageId: ami-0341d95f75f311023
        InstanceType: t3.micro
        KeyName: mod_1_key
        SecurityGroupIds:
          - Ref: mysecuritygroup
        Tags:
          - Key: Name
            Value: MyInstance