version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - node -v
      - npm -v
      - npm install -g @angular/cli@9.0.6
  pre_build:
    commands:
      - cd CodePipeline_S3_AWS
      - npm install
  build:
    commands:
      - ng build --prod
artifacts:
  base-directory: CodePipeline_S3_AWS/dist
  files:
    - "**/*"