version: 0.2
phases:
  install:
    commands:
      - node -v
      - npm -v
      - npm i -g @angular/cli@9.0.6
  pre_build:
    commands:
      - cd CodePipeline_S3_AWS
      - npm ci || npm install
  build:
    commands:
      - ng build --configuration production
artifacts:
  files:
    - "**/*"
  base-directory: CodePipeline_S3_AWS/dist
  